export enum SocketEvent {
    EMAIL_CONFIRMED = 'EMAIL_CONFIRMED',
    AGREEMENT_UPDATED = 'AGREEMENT_UPDATED',
    AGREEMENT_CREATED = 'AGREEMENT_CREATED',
    TRANSACTION_UPDATED = 'TRANSACTION_UPDATED',
    USER_UPDATED = 'USER_UPDATED'
}
