source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'


target 'Equater' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Validator'
  pod 'SwiftLint'

  ####################
  # Google Maps
  ####################
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  
  ####################
  # Firebase
  ####################
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  
  ####################
  # Material UI
  ####################
  
  # Material Text
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  pod 'MaterialComponents/TextControls+FilledTextAreasTheming'
  pod 'MaterialComponents/TextControls+FilledTextFieldsTheming'
  pod 'MaterialComponents/TextControls+OutlinedTextAreasTheming'
  pod 'MaterialComponents/TextControls+OutlinedTextFieldsTheming'
  
  # Material Button
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Buttons+Theming'
  
  # Material Snackbar
  pod 'MaterialComponents/Snackbar'
  pod 'MaterialComponents/Snackbar+TypographyThemer'
  
  # Linear Progress
  pod 'MaterialComponents/ProgressView'
  
  # Ripple
  pod 'MaterialComponents/Ripple'

  ####################
  # End Material UI
  ####################
  
  target 'EquaterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EquaterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
